server:
  port: 8287
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #web:
    #resources:
      #static-locations:
        #- file:///C:\
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-tube?serverTimezone=Asia/Seoul
    username: sbsst
    password: sbs123414

  jpa:
    hibernate:
      #ddl-auto: create #create update none
    show-sql: true
    format_sql: true
    use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      accessKey: AKIAXVDA3VFKKFDGBFHP
      secretKey: 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
    s3:
      bucket: mytube-xanqus
      dir: /
    region:
      static: ap-northeast-2
    stack:
      auto: false

elasticsearch:
  host: hyper-x.kr
  port: 9200