server:
  port: 8287
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  #web:
    #resources:
      #static-locations:
        #- file:///C:\
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.database}?serverTimezone=Asia/Seoul
    username: ${db.username}
    password: ${db.password}

  jpa:
    hibernate:
      #ddl-auto: create #create update none
    show-sql: true
    format_sql: true
    use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      accessKey: ${aws.accessKey}
      secretKey: ${aws.secretKey}
    s3:
      bucket: ${aws.bucket}
      videoDir: video/
      thumbnailDir: thumbnails/
    region:
      static: ${aws.region}
    stack:
      auto: false

elasticsearch:
  host: ${elasticsearch.host}
  port: ${elasticsearch.port}
  username: ${elasticsearch.username}
  password: ${elasticsearch.password}

redis:
  host: ${redis.host}
  port: ${redis.port}