server:
  port: 8287
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  web:
    resources:
      static-locations:
        - file:///C:\
  servlet:
    multipart:
      maxFileSize: 1000MB
      maxRequestSize: 1000MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my-tube?serverTimezone=Asia/Seoul
    username: xanqus
    password: 1234

  jpa:
    hibernate:
      #ddl-auto: create #create update none
    show-sql: true
    format_sql: true
    use_sql_comments: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

cloud:
  aws:
    credentials:
      accessKey: AKIAXVDA3VFKKXBYGCKW
      secretKey: 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
    s3:
      bucket: mytube-xanqus
      dir: /
    region:
      static: ap-northeast-2
    stack:
      auto: false
